/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Uteis.Entradas;
import control.ExibirVagas;
import control.VagasControl;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTextField;
import model.Vagas;
import test.Testes;

/**
 *
 * @author guita
 */
public class Tela extends javax.swing.JFrame {
   // Timer timer = new Timer();
   

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
      //  this.MostrarVagas();
        setLocationRelativeTo(null);
        
        
//        Timer timer = new Timer();
//        TimerTask exibirvagas = new ExibirVagas();
//        
//        timer.schedule(exibirvagas, 2000);
    }
    
//    public final void MostrarVagas() {
//        int delay = 2000;  
//        int interval = 10000;
//        ImageIcon imgVerdeReto = new ImageIcon(getClass().getResource("/imagens/VerdeReto.png"));
//        ImageIcon imgVerdeTorto = new ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"));
//        ImageIcon imgVermelhoReto = new ImageIcon(getClass().getResource("/imagens/VermelhoReto.png"));
//        ImageIcon imgVermelhoTorto = new ImageIcon(getClass().getResource("/imagens/VermelhoTorto.png"));
//
//        JLabel[] ListaLbls = getLbl();
//
//        //Lista de vagas em 45 graus
//        List<Integer> lista45 = Arrays.asList(new Integer[]{14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
//            31, 31, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 51, 52, 53, 54,
//            55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66});
//
//        timer.scheduleAtFixedRate(new TimerTask() {
//            @Override
//            public void run() {
//                try {
//                    VagasControl vagasControl = new VagasControl();
//                    ArrayList<Vagas> listaVagas = vagasControl.Read();
//
//                    for (int i = 0; i < listaVagas.size(); i++) {
//
//                        if (listaVagas.get(i).getVaga().equals("0")) {
//                            //Verifica se a vaga esta livre
//                            if (lista45.contains(i + 1)) {
//                                //Verifica se a vaga está em 45 graus para inserir a imagem correta
//                                ListaLbls[i].setIcon(imgVerdeTorto);
//                            } else {
//                                ListaLbls[i].setIcon(imgVerdeReto);
//                            }
//                        } else {
//                            if (lista45.contains(i + 1)) {
//                                //Verifica se a vaga está em 45 graus para inserir a imagem correta
//                                ListaLbls[i].setIcon(imgVermelhoTorto);
//                            } else {
//                                ListaLbls[i].setIcon(imgVermelhoReto);
//                            }
//                        }
//                    }
//                } catch (Exception e) {
//                    System.out.println(e);
//                }
//            }
//        }, delay, interval);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntLateral = new javax.swing.JButton();
        bntPrincipal = new javax.swing.JButton();
        lblQualVaga = new javax.swing.JLabel();
        lblMapa = new javax.swing.JLabel();
        lblVerde_V67 = new javax.swing.JLabel();
        lblVerde_V34 = new javax.swing.JLabel();
        lblVerde_V66 = new javax.swing.JLabel();
        lblVerde_V50 = new javax.swing.JLabel();
        lblVerde_V1 = new javax.swing.JLabel();
        lblVerde_V2 = new javax.swing.JLabel();
        lblVerde_V3 = new javax.swing.JLabel();
        lblVerde_V4 = new javax.swing.JLabel();
        lblVerde_V5 = new javax.swing.JLabel();
        lblVerde_V6 = new javax.swing.JLabel();
        lblVerde_V7 = new javax.swing.JLabel();
        lblVerde_V8 = new javax.swing.JLabel();
        lblVerde_V9 = new javax.swing.JLabel();
        lblVerde_V10 = new javax.swing.JLabel();
        lblVerde_V11 = new javax.swing.JLabel();
        lblVerde_V12 = new javax.swing.JLabel();
        lblVerde_V13 = new javax.swing.JLabel();
        lblVerde_V68 = new javax.swing.JLabel();
        lblVerde_V69 = new javax.swing.JLabel();
        lblVerde_V70 = new javax.swing.JLabel();
        lblVerde_V71 = new javax.swing.JLabel();
        lblVerde_V72 = new javax.swing.JLabel();
        lblVerde_V73 = new javax.swing.JLabel();
        lblVerde_V74 = new javax.swing.JLabel();
        lblVerde_V75 = new javax.swing.JLabel();
        lblVerde_V76 = new javax.swing.JLabel();
        lblVerde_V77 = new javax.swing.JLabel();
        lblVerde_V78 = new javax.swing.JLabel();
        lblVerde_V48 = new javax.swing.JLabel();
        lblVerde_V49 = new javax.swing.JLabel();
        lblVerde_V14 = new javax.swing.JLabel();
        lblVerde_V15 = new javax.swing.JLabel();
        lblVerde_V16 = new javax.swing.JLabel();
        lblVerde_V17 = new javax.swing.JLabel();
        lblVerde_V18 = new javax.swing.JLabel();
        lblVerde_V19 = new javax.swing.JLabel();
        lblVerde_V20 = new javax.swing.JLabel();
        lblVerde_V21 = new javax.swing.JLabel();
        lblVerde_V22 = new javax.swing.JLabel();
        lblVerde_V23 = new javax.swing.JLabel();
        lblVerde_V24 = new javax.swing.JLabel();
        lblVerde_V25 = new javax.swing.JLabel();
        lblVerde_V26 = new javax.swing.JLabel();
        lblVerde_V27 = new javax.swing.JLabel();
        lblVerde_V28 = new javax.swing.JLabel();
        lblVerde_V29 = new javax.swing.JLabel();
        lblVerde_V30 = new javax.swing.JLabel();
        lblVerde_V31 = new javax.swing.JLabel();
        lblVerde_V32 = new javax.swing.JLabel();
        lblVerde_V33 = new javax.swing.JLabel();
        lblVerde_V35 = new javax.swing.JLabel();
        lblVerde_V36 = new javax.swing.JLabel();
        lblVerde_V37 = new javax.swing.JLabel();
        lblVerde_V38 = new javax.swing.JLabel();
        lblVerde_V39 = new javax.swing.JLabel();
        lblVerde_V47 = new javax.swing.JLabel();
        lblVerde_V46 = new javax.swing.JLabel();
        lblVerde_V45 = new javax.swing.JLabel();
        lblVerde_V44 = new javax.swing.JLabel();
        lblVerde_V43 = new javax.swing.JLabel();
        lblVerde_V42 = new javax.swing.JLabel();
        lblVerde_V41 = new javax.swing.JLabel();
        lblVerde_V40 = new javax.swing.JLabel();
        lblVerde_V51 = new javax.swing.JLabel();
        lblVerde_V52 = new javax.swing.JLabel();
        lblVerde_V53 = new javax.swing.JLabel();
        lblVerde_V54 = new javax.swing.JLabel();
        lblVerde_V55 = new javax.swing.JLabel();
        lblVerde_V56 = new javax.swing.JLabel();
        lblVerde_V57 = new javax.swing.JLabel();
        lblVerde_V58 = new javax.swing.JLabel();
        lblVerde_V59 = new javax.swing.JLabel();
        lblVerde_V60 = new javax.swing.JLabel();
        lblVerde_V61 = new javax.swing.JLabel();
        lblVerde_V62 = new javax.swing.JLabel();
        lblVerde_V63 = new javax.swing.JLabel();
        lblVerde_V64 = new javax.swing.JLabel();
        lblVerde_V65 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        bntLateral.setText("Lateral");
        bntLateral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntLateralActionPerformed(evt);
            }
        });
        getContentPane().add(bntLateral);
        bntLateral.setBounds(750, 670, 100, 23);

        bntPrincipal.setText("Principal");
        bntPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(bntPrincipal);
        bntPrincipal.setBounds(560, 670, 100, 23);

        lblQualVaga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblQualVaga);
        lblQualVaga.setBounds(620, 730, 200, 14);

        lblMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mapa.png"))); // NOI18N
        lblMapa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblMapa);
        lblMapa.setBounds(10, -30, 1350, 1090);

        lblVerde_V67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeReto.png"))); // NOI18N
        getContentPane().add(lblVerde_V67);
        lblVerde_V67.setBounds(220, 340, 20, 26);

        lblVerde_V34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V34);
        lblVerde_V34.setBounds(1040, 160, 40, 14);

        lblVerde_V66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V66);
        lblVerde_V66.setBounds(380, 50, 40, 14);

        lblVerde_V50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeReto.png"))); // NOI18N
        getContentPane().add(lblVerde_V50);
        lblVerde_V50.setBounds(820, 50, 20, 26);

        lblVerde_V1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeReto.png"))); // NOI18N
        getContentPane().add(lblVerde_V1);
        lblVerde_V1.setBounds(340, 940, 20, 26);

        lblVerde_V2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeReto.png"))); // NOI18N
        getContentPane().add(lblVerde_V2);
        lblVerde_V2.setBounds(340, 910, 20, 26);

        lblVerde_V3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeReto.png"))); // NOI18N
        getContentPane().add(lblVerde_V3);
        lblVerde_V3.setBounds(340, 880, 20, 26);

        lblVerde_V4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeReto.png"))); // NOI18N
        getContentPane().add(lblVerde_V4);
        lblVerde_V4.setBounds(340, 850, 20, 26);

        lblVerde_V5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeReto.png"))); // NOI18N
        getContentPane().add(lblVerde_V5);
        lblVerde_V5.setBounds(340, 710, 20, 26);

        lblVerde_V6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeReto.png"))); // NOI18N
        getContentPane().add(lblVerde_V6);
        lblVerde_V6.setBounds(340, 680, 20, 26);

        lblVerde_V7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeReto.png"))); // NOI18N
        getContentPane().add(lblVerde_V7);
        lblVerde_V7.setBounds(340, 650, 20, 26);

        lblVerde_V8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeReto.png"))); // NOI18N
        getContentPane().add(lblVerde_V8);
        lblVerde_V8.setBounds(340, 620, 20, 26);

        lblVerde_V9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeReto.png"))); // NOI18N
        getContentPane().add(lblVerde_V9);
        lblVerde_V9.setBounds(340, 590, 20, 26);

        lblVerde_V10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeReto.png"))); // NOI18N
        getContentPane().add(lblVerde_V10);
        lblVerde_V10.setBounds(340, 470, 20, 26);

        lblVerde_V11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeReto.png"))); // NOI18N
        getContentPane().add(lblVerde_V11);
        lblVerde_V11.setBounds(340, 440, 20, 26);

        lblVerde_V12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeReto.png"))); // NOI18N
        getContentPane().add(lblVerde_V12);
        lblVerde_V12.setBounds(340, 410, 20, 26);

        lblVerde_V13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeReto.png"))); // NOI18N
        getContentPane().add(lblVerde_V13);
        lblVerde_V13.setBounds(340, 380, 20, 26);

        lblVerde_V68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeReto.png"))); // NOI18N
        getContentPane().add(lblVerde_V68);
        lblVerde_V68.setBounds(220, 370, 20, 26);

        lblVerde_V69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeReto.png"))); // NOI18N
        getContentPane().add(lblVerde_V69);
        lblVerde_V69.setBounds(220, 400, 20, 26);

        lblVerde_V70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeReto.png"))); // NOI18N
        getContentPane().add(lblVerde_V70);
        lblVerde_V70.setBounds(220, 430, 20, 26);

        lblVerde_V71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeReto.png"))); // NOI18N
        getContentPane().add(lblVerde_V71);
        lblVerde_V71.setBounds(220, 460, 20, 26);

        lblVerde_V72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeReto.png"))); // NOI18N
        getContentPane().add(lblVerde_V72);
        lblVerde_V72.setBounds(220, 490, 20, 26);

        lblVerde_V73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeReto.png"))); // NOI18N
        getContentPane().add(lblVerde_V73);
        lblVerde_V73.setBounds(220, 600, 20, 26);

        lblVerde_V74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeReto.png"))); // NOI18N
        getContentPane().add(lblVerde_V74);
        lblVerde_V74.setBounds(220, 630, 20, 26);

        lblVerde_V75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeReto.png"))); // NOI18N
        getContentPane().add(lblVerde_V75);
        lblVerde_V75.setBounds(220, 660, 20, 26);

        lblVerde_V76.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeReto.png"))); // NOI18N
        getContentPane().add(lblVerde_V76);
        lblVerde_V76.setBounds(220, 690, 20, 26);

        lblVerde_V77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeReto.png"))); // NOI18N
        getContentPane().add(lblVerde_V77);
        lblVerde_V77.setBounds(220, 720, 20, 26);

        lblVerde_V78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeReto.png"))); // NOI18N
        getContentPane().add(lblVerde_V78);
        lblVerde_V78.setBounds(220, 750, 20, 26);

        lblVerde_V48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeReto.png"))); // NOI18N
        getContentPane().add(lblVerde_V48);
        lblVerde_V48.setBounds(820, 110, 20, 26);

        lblVerde_V49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeReto.png"))); // NOI18N
        getContentPane().add(lblVerde_V49);
        lblVerde_V49.setBounds(820, 80, 20, 26);

        lblVerde_V14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V14);
        lblVerde_V14.setBounds(400, 290, 40, 14);

        lblVerde_V15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V15);
        lblVerde_V15.setBounds(430, 290, 40, 14);

        lblVerde_V16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V16);
        lblVerde_V16.setBounds(450, 290, 40, 14);

        lblVerde_V17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V17);
        lblVerde_V17.setBounds(470, 290, 40, 14);

        lblVerde_V18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V18);
        lblVerde_V18.setBounds(500, 290, 40, 14);

        lblVerde_V19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V19);
        lblVerde_V19.setBounds(520, 290, 40, 14);

        lblVerde_V20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V20);
        lblVerde_V20.setBounds(540, 290, 40, 14);

        lblVerde_V21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V21);
        lblVerde_V21.setBounds(570, 290, 40, 14);

        lblVerde_V22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V22);
        lblVerde_V22.setBounds(590, 290, 40, 14);

        lblVerde_V23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V23);
        lblVerde_V23.setBounds(610, 290, 40, 14);

        lblVerde_V24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V24);
        lblVerde_V24.setBounds(630, 290, 40, 14);

        lblVerde_V25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V25);
        lblVerde_V25.setBounds(660, 290, 40, 14);

        lblVerde_V26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V26);
        lblVerde_V26.setBounds(680, 290, 40, 14);

        lblVerde_V27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V27);
        lblVerde_V27.setBounds(700, 290, 40, 14);

        lblVerde_V28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V28);
        lblVerde_V28.setBounds(920, 200, 40, 14);

        lblVerde_V29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V29);
        lblVerde_V29.setBounds(940, 200, 40, 14);

        lblVerde_V30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V30);
        lblVerde_V30.setBounds(960, 200, 40, 14);

        lblVerde_V31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V31);
        lblVerde_V31.setBounds(980, 200, 40, 14);

        lblVerde_V32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V32);
        lblVerde_V32.setBounds(1010, 200, 40, 14);

        lblVerde_V33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V33);
        lblVerde_V33.setBounds(1030, 200, 40, 14);

        lblVerde_V35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V35);
        lblVerde_V35.setBounds(1010, 160, 40, 14);

        lblVerde_V36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V36);
        lblVerde_V36.setBounds(990, 160, 40, 14);

        lblVerde_V37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V37);
        lblVerde_V37.setBounds(970, 160, 40, 14);

        lblVerde_V38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V38);
        lblVerde_V38.setBounds(940, 160, 40, 14);

        lblVerde_V39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V39);
        lblVerde_V39.setBounds(920, 160, 40, 14);

        lblVerde_V47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V47);
        lblVerde_V47.setBounds(920, 100, 40, 14);

        lblVerde_V46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V46);
        lblVerde_V46.setBounds(940, 100, 40, 14);

        lblVerde_V45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V45);
        lblVerde_V45.setBounds(960, 100, 40, 14);

        lblVerde_V44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V44);
        lblVerde_V44.setBounds(980, 100, 40, 14);

        lblVerde_V43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V43);
        lblVerde_V43.setBounds(1010, 100, 40, 14);

        lblVerde_V42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V42);
        lblVerde_V42.setBounds(1030, 100, 40, 14);

        lblVerde_V41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V41);
        lblVerde_V41.setBounds(1050, 100, 40, 14);

        lblVerde_V40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V40);
        lblVerde_V40.setBounds(1080, 100, 40, 14);

        lblVerde_V51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V51);
        lblVerde_V51.setBounds(720, 50, 40, 14);

        lblVerde_V52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V52);
        lblVerde_V52.setBounds(700, 50, 40, 14);

        lblVerde_V53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V53);
        lblVerde_V53.setBounds(680, 50, 40, 14);

        lblVerde_V54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V54);
        lblVerde_V54.setBounds(650, 50, 40, 14);

        lblVerde_V55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V55);
        lblVerde_V55.setBounds(630, 50, 40, 14);

        lblVerde_V56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V56);
        lblVerde_V56.setBounds(610, 50, 40, 14);

        lblVerde_V57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V57);
        lblVerde_V57.setBounds(590, 50, 40, 14);

        lblVerde_V58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V58);
        lblVerde_V58.setBounds(560, 50, 40, 14);

        lblVerde_V59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V59);
        lblVerde_V59.setBounds(540, 50, 40, 14);

        lblVerde_V60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V60);
        lblVerde_V60.setBounds(520, 50, 40, 14);

        lblVerde_V61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V61);
        lblVerde_V61.setBounds(490, 50, 40, 14);

        lblVerde_V62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V62);
        lblVerde_V62.setBounds(470, 50, 40, 14);

        lblVerde_V63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V63);
        lblVerde_V63.setBounds(450, 50, 40, 14);

        lblVerde_V64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V64);
        lblVerde_V64.setBounds(430, 50, 40, 14);

        lblVerde_V65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VerdeTorto.png"))); // NOI18N
        getContentPane().add(lblVerde_V65);
        lblVerde_V65.setBounds(400, 50, 40, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPrincipalActionPerformed
        // TODO add your handling code here:

        VagasControl vagasControl = new VagasControl();

        int vaga = vagasControl.EncotrarMaisProxima(vagasControl.Read(), Entradas.PRINCIPAL);
        if (vaga == -1) {
            lblQualVaga.setText("Estacionamento lotado");
        } else {
            lblQualVaga.setText("A vaga mais próxima é a vaga " + vaga);
        }
    }//GEN-LAST:event_bntPrincipalActionPerformed

    private void bntLateralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntLateralActionPerformed
        // TODO add your handling code here:
        VagasControl vagasControl = new VagasControl();

        int vaga = vagasControl.EncotrarMaisProxima(vagasControl.Read(), Entradas.SECUNDARIA);
        if (vaga == -1) {
            lblQualVaga.setText("Estacionamento lotado");
        } else {
            lblQualVaga.setText("A vaga mais próxima é a vaga " + vaga);
        }
    }//GEN-LAST:event_bntLateralActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntLateral;
    private javax.swing.JButton bntPrincipal;
    private javax.swing.JLabel lblMapa;
    private javax.swing.JLabel lblQualVaga;
    private javax.swing.JLabel lblVerde_V1;
    private javax.swing.JLabel lblVerde_V10;
    private javax.swing.JLabel lblVerde_V11;
    private javax.swing.JLabel lblVerde_V12;
    private javax.swing.JLabel lblVerde_V13;
    private javax.swing.JLabel lblVerde_V14;
    private javax.swing.JLabel lblVerde_V15;
    private javax.swing.JLabel lblVerde_V16;
    private javax.swing.JLabel lblVerde_V17;
    private javax.swing.JLabel lblVerde_V18;
    private javax.swing.JLabel lblVerde_V19;
    private javax.swing.JLabel lblVerde_V2;
    private javax.swing.JLabel lblVerde_V20;
    private javax.swing.JLabel lblVerde_V21;
    private javax.swing.JLabel lblVerde_V22;
    private javax.swing.JLabel lblVerde_V23;
    private javax.swing.JLabel lblVerde_V24;
    private javax.swing.JLabel lblVerde_V25;
    private javax.swing.JLabel lblVerde_V26;
    private javax.swing.JLabel lblVerde_V27;
    private javax.swing.JLabel lblVerde_V28;
    private javax.swing.JLabel lblVerde_V29;
    private javax.swing.JLabel lblVerde_V3;
    private javax.swing.JLabel lblVerde_V30;
    private javax.swing.JLabel lblVerde_V31;
    private javax.swing.JLabel lblVerde_V32;
    private javax.swing.JLabel lblVerde_V33;
    private javax.swing.JLabel lblVerde_V34;
    private javax.swing.JLabel lblVerde_V35;
    private javax.swing.JLabel lblVerde_V36;
    private javax.swing.JLabel lblVerde_V37;
    private javax.swing.JLabel lblVerde_V38;
    private javax.swing.JLabel lblVerde_V39;
    private javax.swing.JLabel lblVerde_V4;
    private javax.swing.JLabel lblVerde_V40;
    private javax.swing.JLabel lblVerde_V41;
    private javax.swing.JLabel lblVerde_V42;
    private javax.swing.JLabel lblVerde_V43;
    private javax.swing.JLabel lblVerde_V44;
    private javax.swing.JLabel lblVerde_V45;
    private javax.swing.JLabel lblVerde_V46;
    private javax.swing.JLabel lblVerde_V47;
    private javax.swing.JLabel lblVerde_V48;
    private javax.swing.JLabel lblVerde_V49;
    private javax.swing.JLabel lblVerde_V5;
    private javax.swing.JLabel lblVerde_V50;
    private javax.swing.JLabel lblVerde_V51;
    private javax.swing.JLabel lblVerde_V52;
    private javax.swing.JLabel lblVerde_V53;
    private javax.swing.JLabel lblVerde_V54;
    private javax.swing.JLabel lblVerde_V55;
    private javax.swing.JLabel lblVerde_V56;
    private javax.swing.JLabel lblVerde_V57;
    private javax.swing.JLabel lblVerde_V58;
    private javax.swing.JLabel lblVerde_V59;
    private javax.swing.JLabel lblVerde_V6;
    private javax.swing.JLabel lblVerde_V60;
    private javax.swing.JLabel lblVerde_V61;
    private javax.swing.JLabel lblVerde_V62;
    private javax.swing.JLabel lblVerde_V63;
    private javax.swing.JLabel lblVerde_V64;
    private javax.swing.JLabel lblVerde_V65;
    private javax.swing.JLabel lblVerde_V66;
    private javax.swing.JLabel lblVerde_V67;
    private javax.swing.JLabel lblVerde_V68;
    private javax.swing.JLabel lblVerde_V69;
    private javax.swing.JLabel lblVerde_V7;
    private javax.swing.JLabel lblVerde_V70;
    private javax.swing.JLabel lblVerde_V71;
    private javax.swing.JLabel lblVerde_V72;
    private javax.swing.JLabel lblVerde_V73;
    private javax.swing.JLabel lblVerde_V74;
    private javax.swing.JLabel lblVerde_V75;
    private javax.swing.JLabel lblVerde_V76;
    private javax.swing.JLabel lblVerde_V77;
    private javax.swing.JLabel lblVerde_V78;
    private javax.swing.JLabel lblVerde_V8;
    private javax.swing.JLabel lblVerde_V9;
    // End of variables declaration//GEN-END:variables

    public JLabel[] getLbl() {
        //Pega os valores de todos os labels referente as vagas
        JLabel listaLbl[] = new JLabel[78];

        listaLbl[0] = this.lblVerde_V1;
        listaLbl[1] = this.lblVerde_V2;
        listaLbl[2] = this.lblVerde_V3;
        listaLbl[3] = this.lblVerde_V4;
        listaLbl[4] = this.lblVerde_V5;
        listaLbl[5] = this.lblVerde_V6;
        listaLbl[6] = this.lblVerde_V7;
        listaLbl[7] = this.lblVerde_V8;
        listaLbl[8] = this.lblVerde_V9;
        listaLbl[9] = this.lblVerde_V10;

        listaLbl[10] = this.lblVerde_V11;
        listaLbl[11] = this.lblVerde_V12;
        listaLbl[12] = this.lblVerde_V13;
        listaLbl[13] = this.lblVerde_V14;
        listaLbl[14] = this.lblVerde_V15;
        listaLbl[15] = this.lblVerde_V16;
        listaLbl[16] = this.lblVerde_V17;
        listaLbl[17] = this.lblVerde_V18;
        listaLbl[18] = this.lblVerde_V19;
        listaLbl[19] = this.lblVerde_V20;

        listaLbl[20] = this.lblVerde_V21;
        listaLbl[21] = this.lblVerde_V22;
        listaLbl[22] = this.lblVerde_V23;
        listaLbl[23] = this.lblVerde_V24;
        listaLbl[24] = this.lblVerde_V25;
        listaLbl[25] = this.lblVerde_V26;
        listaLbl[26] = this.lblVerde_V27;
        listaLbl[27] = this.lblVerde_V28;
        listaLbl[28] = this.lblVerde_V29;
        listaLbl[29] = this.lblVerde_V30;

        listaLbl[30] = this.lblVerde_V31;
        listaLbl[31] = this.lblVerde_V32;
        listaLbl[32] = this.lblVerde_V33;
        listaLbl[33] = this.lblVerde_V34;
        listaLbl[34] = this.lblVerde_V35;
        listaLbl[35] = this.lblVerde_V36;
        listaLbl[36] = this.lblVerde_V37;
        listaLbl[37] = this.lblVerde_V38;
        listaLbl[38] = this.lblVerde_V39;
        listaLbl[39] = this.lblVerde_V40;

        listaLbl[40] = this.lblVerde_V41;
        listaLbl[41] = this.lblVerde_V42;
        listaLbl[42] = this.lblVerde_V43;
        listaLbl[43] = this.lblVerde_V44;
        listaLbl[44] = this.lblVerde_V45;
        listaLbl[45] = this.lblVerde_V46;
        listaLbl[46] = this.lblVerde_V47;
        listaLbl[47] = this.lblVerde_V48;
        listaLbl[48] = this.lblVerde_V49;
        listaLbl[49] = this.lblVerde_V50;

        listaLbl[50] = this.lblVerde_V51;
        listaLbl[51] = this.lblVerde_V52;
        listaLbl[52] = this.lblVerde_V53;
        listaLbl[53] = this.lblVerde_V54;
        listaLbl[54] = this.lblVerde_V55;
        listaLbl[55] = this.lblVerde_V56;
        listaLbl[56] = this.lblVerde_V57;
        listaLbl[57] = this.lblVerde_V58;
        listaLbl[58] = this.lblVerde_V59;
        listaLbl[59] = this.lblVerde_V60;

        listaLbl[60] = this.lblVerde_V61;
        listaLbl[61] = this.lblVerde_V62;
        listaLbl[62] = this.lblVerde_V63;
        listaLbl[63] = this.lblVerde_V64;
        listaLbl[64] = this.lblVerde_V65;
        listaLbl[65] = this.lblVerde_V66;
        listaLbl[66] = this.lblVerde_V67;
        listaLbl[67] = this.lblVerde_V68;
        listaLbl[68] = this.lblVerde_V69;
        listaLbl[69] = this.lblVerde_V70;

        listaLbl[70] = this.lblVerde_V71;
        listaLbl[71] = this.lblVerde_V72;
        listaLbl[72] = this.lblVerde_V73;
        listaLbl[73] = this.lblVerde_V74;
        listaLbl[74] = this.lblVerde_V75;
        listaLbl[75] = this.lblVerde_V76;
        listaLbl[76] = this.lblVerde_V77;
        listaLbl[77] = this.lblVerde_V78;

        return listaLbl;
    }
}
